<?php
return [
        'app\components\auth\UserInitialService' => 'app\components\auth\UserInitialService',
        'app\components\client\ClientRepo' => 'app\components\client\ClientRepo',
        'app\components\core\FileRepo' => 'app\components\core\FileRepo',
        'app\components\core\FileService' => 'app\components\core\FileService',
        'app\components\core\TaxonomyRepo' => 'app\components\core\TaxonomyRepo',
        'app\components\core\TaxonomyService' => 'app\components\core\TaxonomyService',
        'app\components\core\TaxonomyTypeRepo' => 'app\components\core\TaxonomyTypeRepo',
        'app\components\core\TaxonomyTypeService' => 'app\components\core\TaxonomyTypeService',
        'app\components\datafeed\DatafeedRepo' => 'app\components\datafeed\DatafeedRepo',
        'app\components\datafeed\DatafeedService' => 'app\components\datafeed\DatafeedService',
        'app\components\datafeed\FeedFileRepo' => 'app\components\datafeed\FeedFileRepo',
        'app\components\platform\PlatformRepo' => 'app\components\platform\PlatformRepo',
        'app\components\user\UserRepo' => 'app\components\user\UserRepo',
        'app\components\user\UserService' => 'app\components\user\UserService',
        'app\components\version\DataVersionRepo' => 'app\components\version\DataVersionRepo',
        'v1\components\client\ClientSearchService' => 'v1\components\client\ClientSearchService',
        'v1\components\core\TaxonomySearchService' => 'v1\components\core\TaxonomySearchService',
        'v1\components\core\TaxonomyTypeSearchService' => 'v1\components\core\TaxonomyTypeSearchService',
        'v1\components\datafeed\DatafeedSearchService' => 'v1\components\datafeed\DatafeedSearchService',
        'v1\components\datafeed\FeedFileCreateService' => 'v1\components\datafeed\FeedFileCreateService',
        'v1\components\datafeed\FeedFileSearchService' => 'v1\components\datafeed\FeedFileSearchService',
        'v1\components\datafeed\FeedFileUpdateService' => 'v1\components\datafeed\FeedFileUpdateService',
        'v1\components\file\FileSearchService' => 'v1\components\file\FileSearchService',
        'v1\components\platform\PlatformSearchService' => 'v1\components\platform\PlatformSearchService',
        'v1\components\user\UserSearchService' => 'v1\components\user\UserSearchService',
        'v1\components\version\DataVersionSearchService' => 'v1\components\version\DataVersionSearchService',
    ];
